### ISSUE TITLE
cant load blib subpackage

### ISSUE THREAD

**Issue by clankill3r** [LucaRood/Blib#1]
hi Lucas,
- **Platform:**Windows
- **Blender version:** 2.77

I try to get blib working using your readme:
https://github.com/LucaRood/Blib#use-blib-from-the-blender-python-console

I installed it here:
![blib](https://cloud.githubusercontent.com/assets/738650/14323876/b36ccf78-fc22-11e5-8a45-165efe43afee.PNG)

This is the error I get:

> > > > from blib.cycles import bimport, bexport
> > > > Traceback (most recent call last):
> > > >   File "<blender_console>", line 1, in <module>
> > > > ImportError: cannot import name 'bimport'

I think blib is not found at all.

Hope you can help.

**Comment by clankill3r** [comment]
Whoah, this is the strangest unpack bug I have ever encountered. All files ar with a .md instead of .py.
Unpacking the rar again solved the problem.

**Comment by LunaRood** [comment]
You probably just copied the files from the **/doc/blib** directory by accident, instead of the files in **/blib**. As those are the documentation files, they are indeed **.md**.
