### ISSUE TITLE
Developing Blib subpackage for AN

### ISSUE THREAD

**Issue by clankill3r** [LucaRood/Blib#2]
I know you stated this is currently not possible, which is fine and understandable.

I was just hoping you could provide some info of how things are going down the road.
And I was wondering how hard it will be to add suport for another asset type.

What I want to do is make it possible to export node trees created in animation nodes (AN).
Main reason behind this is to make a node tree more usable in other sketches.
In case you don't klnow AN (which I really doubt), here is a video.
https://www.youtube.com/watch?v=hnlUhlkxQZU

**Comment by LunaRood** [comment]
Well, I plan to port the Cycles node group code, out of the **cycles** subpackage, and into a **node_tree** subpackage, that will then be expanded to support any type of node tree.

This should not be very difficult at all, as the code is mostly there, but it'll take some refactoring. It will, however, be a while until I am able to work on that, as I am currently busy with some other projects as well.

**Comment by clankill3r** [comment]
Ok, I keep an eye on Blib then. I have plenty stuff on my own as well :)

**Comment by LunaRood** [comment]
I'm closing this issue as irrelevant, because I'll be adding support for any type of node tree anyway.
